# Generated by Django 3.2.25 on 2026-02-03 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_fitnessclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('available_spots', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('fitness_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='classes.fitnessclass')),
            ],
            options={
                'verbose_name_plural': 'Class Schedules',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
