# Generated by Django 3.2.25 on 2026-02-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='available_spots',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
