# Generated by Django 3.2.25 on 2026-03-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_classschedule_available_spots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessclass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='classes/'),
        ),
    ]
