# Generated by Django 3.2.25 on 2026-02-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_usermembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptier',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Stripe Price ID for subscriptions', max_length=255),
        ),
        migrations.AddField(
            model_name='membershiptier',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Stripe Product ID', max_length=255),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID', max_length=255),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe Subscription ID', max_length=255),
        ),
    ]
